### PR TITLE
Issue 23: Suppress some Stan output

### LINKED ISSUE #23: Large amount of Stan output in vignette
**Describe the bug**

The vignette "Wastewater informed forecasting: fit to simulated data" has a large amount of Stan output which makes it difficult to read.

**Impact**

Minimal impact.

**To Reproduce**

Look at https://didactic-doodle-g3m75r1.pages.github.io/articles/toy_data_vignette.html.

**Suggestion**

I suggest suppressing some of the Stan output to make the vignette easier to read.

### PR DESCRIPTION
**Pull request by athowes**
Closes #23.

I've limited the amount of Stan output that is shown in the vignette. I've also fixed the display of one header at the end.

### CODE REVIEW

**Comment by kaitejohnson** [comment]
Thanks for doing this @athowes! I will approve as soon as we get the test data fixed and merge over from the developed on codebase (that was our decided on temporary solution for the change in the stan rng, which is why this is failing the CI test)

**Comment by athowes** [comment]
There are some other stylistic / formatting things I'd likely change about the vignette. Let me know if worthwhile to go through and suggest those changes / now is a reasonable time to do that. (I'm interested to get up to speed with the model and doing this is one way to start with that.)

**Comment by kaitejohnson** [comment]
@athowes That would be awesome, please go ahead!

**Review by kaitejohnson — APPROVED** [review]
LGTM!

**Comment by athowes** [comment]
(This isn't merged by the way?)

**Pull request merged**
